In [2]:
x0,x1,x2=2.,3.,5,
bias,w1,w2=1,0.2,0.5

In [3]:
x=[x0,x1,x2]


w=[bias,w1,w2]

In [ ]:
sum=0
for i in range(len(x)):
    sum+=x[i]*w[i]


print(sum)

5.1


In [ ]:
import numpy as np

x_vec,y_vec=np.array(x),np.array(w)

result=(x_vec.transpose()).dot(y_vec)
print(result)

5.1


In [4]:
import torch
print(torch.__version__)

2.11.0+cu128


In [5]:
print(torch.cuda.get_device_name(0))

Tesla T4


In [ ]:
#Ways of creating tensors

a=torch.empty(2,3)  #these are garbage values
print(type(a))

<class 'torch.Tensor'>


In [ ]:
torch.zeros(3,3)  #we can make these of ones,rand

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2,3)  #rand values between zero and ones .each times, it generates random values so, we need reproducibility
                 #for this, we can use torch seed.



tensor([[0.9524, 0.6253, 0.2851],
        [0.7467, 0.9181, 0.7256]])

In [ ]:
torch.manual_seed(101)
torch.rand(4,4)

tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716],
        [0.5834, 0.7521, 0.7649, 0.1443]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(1,100,4)

tensor([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69,
        73, 77, 81, 85, 89, 93, 97])

In [ ]:
torch.linspace(1,10,99)   #same evenly spaced values

tensor([ 1.0000,  1.0918,  1.1837,  1.2755,  1.3673,  1.4592,  1.5510,  1.6429,
         1.7347,  1.8265,  1.9184,  2.0102,  2.1020,  2.1939,  2.2857,  2.3776,
         2.4694,  2.5612,  2.6531,  2.7449,  2.8367,  2.9286,  3.0204,  3.1122,
         3.2041,  3.2959,  3.3878,  3.4796,  3.5714,  3.6633,  3.7551,  3.8469,
         3.9388,  4.0306,  4.1224,  4.2143,  4.3061,  4.3980,  4.4898,  4.5816,
         4.6735,  4.7653,  4.8571,  4.9490,  5.0408,  5.1327,  5.2245,  5.3163,
         5.4082,  5.5000,  5.5918,  5.6837,  5.7755,  5.8673,  5.9592,  6.0510,
         6.1429,  6.2347,  6.3265,  6.4184,  6.5102,  6.6020,  6.6939,  6.7857,
         6.8776,  6.9694,  7.0612,  7.1531,  7.2449,  7.3367,  7.4286,  7.5204,
         7.6122,  7.7041,  7.7959,  7.8878,  7.9796,  8.0714,  8.1633,  8.2551,
         8.3469,  8.4388,  8.5306,  8.6224,  8.7143,  8.8061,  8.8980,  8.9898,
         9.0816,  9.1735,  9.2653,  9.3571,  9.4490,  9.5408,  9.6327,  9.7245,
         9.8163,  9.9082, 10.0000])

In [ ]:
#using eye we can make diagonal values

k=torch.eye(4)
#it makes matrix with 1 diagonal ,we can multiply it to make custom diagonal element like

print(5*k)

tensor([[5., 0., 0., 0.],
        [0., 5., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 5.]])


In [ ]:
#using full, we can give shape of tensor and then provide element like:
torch.full((3,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [ ]:
#how to make tensors of shape like other tensors used liek
#let us know we have a tensor of 2,3 dimension
x=torch.tensor([[1,2,3],[4,5,6]])

k=torch.empty_like(x)  #simply, we have to use "like" function
k

tensor([[3616445622929465956, 6067248292779011382, 3617861884368795441],
        [6499030932789866798, 7309453675965983778, 8315168162784306286]])

In [ ]:
#now, we are moving toward data type

r=torch.rand(2,2)
print(r.dtype)

torch.float32


In [ ]:
#using like function for the rand tensor, it dont work so we have to use explicit data conversion for such tensors

q=torch.rand(2,2,dtype=torch.float16)
print(q)

#we can use to() function for type conversion
r=q.to(torch.float64)
print(r)

tensor([[0.3711, 0.0991],
        [0.4937, 0.7261]], dtype=torch.float16)
tensor([[0.3711, 0.0991],
        [0.4937, 0.7261]], dtype=torch.float64)


In [ ]:

#mathematical operations..

x=torch.rand(4,4)

#addition
x+1  #same for sub,mult adn div, // for integer division,mod,power




tensor([[1.8695, 1.0981, 1.3290, 1.8080],
        [1.5859, 1.3518, 1.9628, 1.2238],
        [1.8474, 1.7816, 1.5466, 1.0633],
        [1.1578, 1.7040, 1.0616, 1.3781]])

In [ ]:
dh=torch.arange(-10,20,1.5)
#absolute value as
print(torch.abs(dh))

#we can round off the numbers as:
print(torch.round(dh))

#we can use ceil to get value of upper integer like 2.3 become 3
#same , we can use floor to get lower integer like 2 for 2.3


tensor([10.0000,  8.5000,  7.0000,  5.5000,  4.0000,  2.5000,  1.0000,  0.5000,
         2.0000,  3.5000,  5.0000,  6.5000,  8.0000,  9.5000, 11.0000, 12.5000,
        14.0000, 15.5000, 17.0000, 18.5000])
tensor([-10.,  -8.,  -7.,  -6.,  -4.,  -2.,  -1.,   0.,   2.,   4.,   5.,   6.,
          8.,  10.,  11.,  12.,  14.,  16.,  17.,  18.])


In [ ]:
ps=torch.tensor([1,2,3,4,5,6,7,8,9],dtype=torch.float64)
#we can use clamp to make values in a range like all become low and upper limit
print(ps.clamp(2,4))

tensor([2., 2., 3., 4., 4., 4., 4., 4., 4.], dtype=torch.float64)


In [ ]:
k=torch.randint(size=(2,3),low=4,high=9)
k

print(k.sum())
#for sum along column, we can use dim=0 adn for row, we can use dim=1


tensor(37)


In [ ]:
print(torch.mean(k.float(),dim=0))
k  #likewise, we can compute median,mode,stdd and all,min,max,prod,var for variance


tensor([5.5000, 7.5000, 5.5000])


tensor([[6, 8, 4],
        [5, 7, 7]])

In [ ]:
k.argmax() #position of maximum item ie 8 on 1 position. likewise, we can use argmin


tensor(1)

In [ ]:
#we can use torch.transpose(x) for transpose, dot ,determinant for det and inverse of square matrices
#matmul for multiplication\
#we can do comparisions
a=torch.randint(size=(3,3),low=1,high=9)
b=torch.randint(size=(3,3),low=1,high=9)
a>b

tensor([[False, False,  True],
        [False,  True, False],
        [ True,  True,  True]])

In [ ]:
#torch.log, torch.exp,sqrt
#sigmoid too and softmax too
#relu too

In [ ]:
#when we do operations ,it produce new tensor for output so for better memory management
#we can use inplace to store output in place of any one input tensors

m=torch.rand(2,3)
n=torch.rand(2,3)
m.add_(n)



tensor([[1.4154, 0.8228, 1.0350],
        [0.6240, 1.5667, 0.1582]])

In [ ]:
m  #likethis, we stored result in m

tensor([[1.4154, 0.8228, 1.0350],
        [0.6240, 1.5667, 0.1582]])

In [ ]:
m=torch.tensor([-1,-3,0,0,4,5,6,7])
print(m.relu_()) #relu makes negative and zero number as 0 and positive as same. like we explored, it is used as
                 #activation function to each perceptron

print(m)   #using underscore helps to store resut in m which is done widely in dl

tensor([0, 0, 0, 0, 4, 5, 6, 7])
tensor([0, 0, 0, 0, 4, 5, 6, 7])


In [ ]:
#when we assign or think we copied a value at variable to another using =, we are only referencing new variable to existing variable

#so, doing changes in original variable makes change in its new assigned variable .

#for this, we use clone function
a=torch.tensor([1,2,3,4,5])
b=a.clone()
(print(id(a),id(b)))  #which is different.

137845092664896 137845092666496


In [ ]:
#Doing operation in gpu.
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda') #Now, we make tensors in vram gpu not in ordinary ram


In [ ]:
torch.rand(2,3,device=device)

tensor([[0.6941, 0.0714, 0.3151],
        [0.0764, 0.6683, 0.1244]], device='cuda:0')

In [ ]:
#Moving tensors from cpu to gpu

v=torch.tensor([1,2,3,4,5])
k=v.to(device=device)
k+5

tensor([ 6,  7,  8,  9, 10], device='cuda:0')

In [ ]:
import time
size=10000
mat1_cpu=torch.rand(size,size)
mat2_cpu=torch.rand(size,size)

start_time=time.time()
torch.matmul(mat1_cpu,mat2_cpu)
cpu_time=time.time()-start_time

print("time taken by cpu :",cpu_time)

time taken by cpu : 20.714089155197144


In [ ]:
mat1_gpu=mat1_cpu.to('cuda')
mat2_gpu=mat2_cpu.to('cuda')

start_time=time.time()
torch.matmul(mat1_gpu,mat2_gpu)
torch.cuda.synchronize() # Wait for GPU to finish computations
gpu_time=time.time()-start_time

print("time taken by gpu :",gpu_time)

time taken by gpu : 0.54927659034729


In [ ]:
#Reshaping Tensors,we can use reshape,flatten to convert in 1D tensor,


#Likewise, we can use permute function for custom dimension changhes

c=torch.rand(2,3,4)
print("before permute:",c.shape)

#Now, we have to change its dimension to 3,4,2 we can do as;
r=c.permute(1,2,0)
print("after permute:",r.shape)


before permute: torch.Size([2, 3, 4])
after permute: torch.Size([3, 4, 2])


In [ ]:
#unsqeeze
#It helps to add new dimension in the required place.
dh=torch.rand(224,224,3)
print(dh.unsqueeze(1).shape)



#We can use squeeze for removing any dimensions
print(dh.squeeze(1).shape)

torch.Size([224, 1, 224, 3])
torch.Size([224, 224, 3])


In [ ]:
#How can we convert between numpy arrays and a pytorch tensor

hello=torch.tensor([1,2,3,4])
p=hello.numpy()  #converts tensor into numpy array

print(type(p))

<class 'numpy.ndarray'>


In [ ]:
#to convert numpy into torch tensor

o=torch.from_numpy(p)
type(o)

torch.Tensor